spring:
 jpa:
  database-platform: org.hibernate.dialect.MySQLDialect
  show-sql: false  
  hibernate:
   ddl-auto: create
datasources:
 -
  name: CS_DEFAULT
  url: jdbc:mysql://localhost:3306/CS_DEFAULT
  user: root
  pass: admin123
 -
  name: CS_TEST
  url: jdbc:mysql://localhost:3306/TEST
  user: root
  pass: admin123
 -
  name: CS_DEV
  url: jdbc:mysql://localhost:3306/CS_DEV
  user: root
  pass: admin123

